[package]
name = "vrb-shared-operator-loader"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
libloading.workspace = true
thiserror.workspace = true
vrb-core = { version = "0.1.0", path = "../vrb-core" }
vrb-operators = { version = "0.1.0", path = "../vrb-operators" }
vrb-shared-operators = { version = "0.1.0", path = "../vrb-shared-operators" }
vrb-shared-operator-plugin-api = { version = "0.1.0", path = "../vrb-shared-operator-plugin-api" }
