[workspace]
members = [
    "crates/vrb",
    "crates/vrb-backends",
    "crates/vrb-core",
    "crates/vrb-operators",
    "crates/vrb-plugin-api",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
rust-version = "1.88"

[workspace.dependencies]
anyhow = "1.0.100"
ash = "0.38.0"
libloading = "0.8.9"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
thiserror = "2.0.17"
vrb-core = { path = "crates/vrb-core" }
vrb-plugin-api = { path = "crates/vrb-plugin-api" }
